# src/main/resources/application.yml
spring:
  application:
    name: Pigeon

  data:
    mongodb:
      uri: mongodb://pigeon:123456789@localhost:27017/PigeonSkyRace

jwt:
  secret: f6fbccba3855c01297f5c39e8bd5ef9c4ad57a44c9d3d26032162f59daec4a8c
  expiration:
    time: 3600000